// Exporta el objeto de estilos para ser usado por los componentes.
export const styles = {
    appWrapper: { backgroundColor: '#FFFFFF', minHeight: '100vh', display: 'flex', flexDirection: 'column', paddingTop: '4rem', paddingBottom: '4rem', fontFamily: "'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol'" },
    container: { width: '100%', maxWidth: '1200px', margin: '0 auto', padding: '0 2rem' },
    authContainer: {
        backgroundColor: '#FFFFFF',
        padding: '3rem',
        borderRadius: '1.5rem',
        boxShadow: '0 10px 25px rgba(0, 0, 0, 0.1)',
        textAlign: 'center',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '1.5rem',
        maxWidth: '400px',
        margin: '2rem auto',
    },
    authTitle: {
        margin: '0 0 0.5rem 0',
        fontSize: '2.25rem',
        fontWeight: '800',
        color: '#1F2937',
    },
    authSubtitle: {
        margin: '0 0 2rem 0',
        color: '#6B7280',
    },
    inputGroup: {
        width: '100%',
        position: 'relative',
    },
    inputIcon: {
        position: 'absolute',
        left: '1rem',
        top: '50%',
        transform: 'translateY(-50%)',
        display: 'flex',
        alignItems: 'center',
        color: '#9CA3AF',
    },
    input: {
        width: '100%',
        padding: '1rem 1rem 1rem 3rem',
        fontSize: '1rem',
        border: '1px solid #D1D5DB',
        borderRadius: '0.75rem',
        boxSizing: 'border-box',
        outline: 'none',
        transition: 'border-color 0.3s, box-shadow 0.3s',
        '&:focus': {
            borderColor: '#3B82F6',
            boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.1)',
        },
    },
    inputLabel: { display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', fontWeight: '600', color: '#4b5563' },
    mainHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' },
    header: { margin: 0, fontSize: '2rem', fontWeight: 700, color: '#3B82F6' },
    subtitle: { marginTop: '0.25rem', color: '#6B7280' },
    card: { backgroundColor: 'white', padding: '1.5rem', borderRadius: '1.5rem', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)', marginBottom: '1.5rem', width: '100%', boxSizing: 'border-box' },
    searchSection: { display: 'flex', gap: '0.5rem', width: '100%' },
    searchInput: { flex: 1, padding: '0.75rem 1rem', fontSize: '1rem', border: '2px solid #d1d5db', borderRadius: '0.75rem', outline: 'none' },
    historyToggle: { background: 'none', border: 'none', color: '#3B82F6', cursor: 'pointer', marginTop: '1rem', padding: 0, fontWeight: 600 },
    error: { color: '#ef4444', textAlign: 'center', fontWeight: '600', marginTop: '1rem' },
    weatherHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '1px solid #f3f4f6', paddingBottom: '1rem' },
    weatherCity: { margin: 0, fontSize: '1.5rem', fontWeight: 600 },
    weatherDescription: { margin: '0.25rem 0 0 0', color: '#6B7280', textTransform: 'capitalize' },
    weatherIcon: { width: '60px', height: '60px', marginTop: '-10px', marginRight: '-10px' },
    weatherGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginTop: '1rem' },
    infoCard: { borderRadius: '1rem', padding: '1rem', display: 'flex', alignItems: 'center', gap: '1rem' },
    tempCard: { backgroundColor: '#fff1f2', color: '#be123c' },
    humidityCard: { backgroundColor: '#eff6ff', color: '#2563eb' },
    aiButton: { marginTop: '1.5rem', background: 'linear-gradient(to right, #3B82F6, #2563EB)', color: 'white', border: 'none', borderRadius: '0.75rem', padding: '0.75rem 1.5rem', fontWeight: '600', cursor: 'pointer', transition: 'transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.06)' },
    aiAdvice: { marginTop: '1.5rem', backgroundColor: '#F0F9FF', padding: '1.5rem', borderRadius: '1rem', display: 'flex', flexDirection: 'column', gap: '1rem', alignItems: 'center', border: '1px solid #BFDBFE' },
    aiAdviceIconContainer: { backgroundColor: '#DBEAFE', borderRadius: '9999px', padding: '0.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
    aiAdviceTitle: { margin: '0 0 0.5rem 0', fontWeight: 600, color: '#5b21b6', },
    aiAdviceText: { margin: 0, color: '#4b5563', lineHeight: '1.6' },
    cardTitle: { marginTop: 0, fontWeight: 600, paddingBottom: '0.5rem' },
    mainContentFlexWrapper: {
        display: 'flex',
        flexDirection: 'column',
        marginTop: '2rem', // Moved marginTop here
        alignItems: 'flex-start',
    },
    mainContentArea: {
        width: '100%', // Reverted to 100% to allow dynamic sizing within the larger container
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem', // Space between cards
    },
    historyCard: {
        flexShrink: 0,
        width: '500px',
        maxHeight: 'calc(100vh - 4rem)',
        overflowY: 'auto', // Changed to auto to allow scrolling
        transition: 'width 0.3s ease-in-out, opacity 0.3s ease-in-out',
    },
    historyList: {
        listStyleType: 'none',
        padding: 0,
        margin: '0 0.5rem 0 0',
        maxHeight: '500px', // Aproximadamente 5 elementos de historial
        overflowY: 'auto',
    },
    historyItem: { display: 'flex', alignItems: 'center', gap: '1rem', padding: '1rem', backgroundColor: '#F9FAFB', borderRadius: '1rem', marginBottom: '0.75rem', transition: 'all 0.3s ease-in-out' },
    historyTempBubble: { backgroundColor: '#BFDBFE', color: '#1E40AF', padding: '0.5rem 0.75rem', borderRadius: '9999px', fontWeight: '600', fontSize: '0.875rem' },
    historyCity: { fontWeight: 600, color: '#1e293b' },
    historyDesc: { margin: 0, color: '#64748b', textTransform: 'capitalize', fontSize: '0.875rem' },
    historyDate: { color: '#64748b', fontSize: '0.875rem', marginLeft: 'auto' },
    authToggle: {
        background: 'none',
        border: 'none',
        color: '#3B82F6',
        cursor: 'pointer',
        padding: '0.5rem',
        fontWeight: '600',
        transition: 'color 0.3s',
        '&:hover': {
            color: '#2563EB',
        },
    },
    primaryButton: {
        width: '100%',
        padding: '1rem',
        fontSize: '1rem',
        fontWeight: '600',
        color: '#FFFFFF',
        backgroundColor: '#3B82F6',
        border: 'none',
        borderRadius: '0.75rem',
        cursor: 'pointer',
        transition: 'background-color 0.3s, box-shadow 0.3s',
        boxShadow: '0 4px 6px rgba(59, 130, 246, 0.1)',
        '&:hover': {
            backgroundColor: '#2563EB',
            boxShadow: '0 6px 12px rgba(59, 130, 246, 0.15)',
        },
        '&:disabled': {
            backgroundColor: '#9CA3AF',
            cursor: 'not-allowed',
        },
    },
    planTag: { display: 'inline-block', padding: '0.25rem 0.75rem', borderRadius: '9999px', fontSize: '0.75rem', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'white' },
    freeTag: { color: '#4b5563', backgroundColor: '#e5e7eb' },
    premiumTag: { background: 'linear-gradient(to right, #60A5FA, #3B82F6)', boxShadow: '0 2px 8px rgba(59, 130, 246, 0.4)' },
    proTag: { background: 'linear-gradient(to right, #1D4ED8, #3B82F6)', boxShadow: '0 2px 8px rgba(59, 130, 246, 0.4)' },
    freemiumMessage: { backgroundColor: '#E0F2FE', color: '#1E40AF', padding: '1rem', borderRadius: '0.75rem', marginBottom: '1rem', textAlign: 'center', fontSize: '0.875rem' },
    upgradeButton: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem', background: 'linear-gradient(to right, #3B82F6, #2563EB)', color: 'white', border: 'none', borderRadius: '0.75rem', padding: '0.5rem 1rem', fontWeight: '600', cursor: 'pointer', transition: 'transform 0.2s ease-in-out', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.06)'},
    aiAdviceText: {margin: 0,color: '#4A5568',lineHeight: '1.6',whiteSpace: 'pre-wrap',},
    premiumCardTitle: {
        marginTop: 0,
        fontWeight: 700,
        paddingBottom: '0.5rem',
        color: '#3B82F6', // Un color morado que ya usas en la app
        textAlign: 'center'
    },
    imageGallery: { display: 'flex', gap: '1rem', marginTop: '1rem', marginBottom: '1rem' },
    galleryImage: { width: '80px', height: '80px', borderRadius: '1rem', objectFit: 'cover', border: '2px solid #BFDBFE' },

    };