// Exporta el objeto de estilos para ser usado por los componentes.
export const styles = {
    appWrapper: { backgroundColor: '#f0f7ff', minHeight: '100vh', display: 'flex', paddingTop: '4rem', paddingBottom: '4rem', fontFamily: "'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol'" },
    container: { width: '100%', maxWidth: '1100px', margin: '0 auto', padding: '0 2rem' },
    authContainer: { backgroundColor: 'white', padding: '2.5rem', borderRadius: '1.5rem', boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem', maxWidth: '450px', margin: '0 auto' },
    authTitle: { margin: '1rem 0 0.25rem 0', fontSize: '2rem', fontWeight: '700', color: '#4f46e5' },
    authSubtitle: { margin: '0 0 1.5rem 0', color: '#6b7280' },
    inputGroup: { width: '100%', position: 'relative' },
    inputIcon: { position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)', display: 'flex', alignItems: 'center' },
    input: { width: '100%', padding: '0.75rem 0.75rem 0.75rem 2.5rem', fontSize: '1rem', border: '1px solid #d1d5db', borderRadius: '0.75rem', boxSizing: 'border-box', outline: 'none' },
    mainHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' },
    header: { margin: 0, fontSize: '2rem', fontWeight: 700, color: '#4f46e5' },
    subtitle: { marginTop: '0.25rem', color: '#6b7280' },
    card: { backgroundColor: 'white', padding: '1.5rem', borderRadius: '1.5rem', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)' },
    searchSection: { display: 'flex', gap: '0.5rem' },
    searchInput: { flex: 1, padding: '0.75rem 1rem', fontSize: '1rem', border: '1px solid #d1d5db', borderRadius: '0.75rem', outline: 'none' },
    historyToggle: { background: 'none', border: 'none', color: '#4f46e5', cursor: 'pointer', marginTop: '1rem', padding: 0, fontWeight: 600 },
    error: { color: '#ef4444', textAlign: 'center', fontWeight: '600', marginTop: '1rem' },
    mainContentWrapper: { display: 'flex', flexDirection: 'row', gap: '2rem', alignItems: 'flex-start', transition: 'justify-content 0.5s ease-in-out' },
    leftColumn: { flex: 2, display: 'flex', flexDirection: 'column', gap: '1.5rem', minWidth: '400px' },
    rightColumn: { flex: 1, minWidth: '350px' },
    weatherHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '1px solid #f3f4f6', paddingBottom: '1rem' },
    weatherCity: { margin: 0, fontSize: '1.5rem', fontWeight: 600 },
    weatherDescription: { margin: '0.25rem 0 0 0', color: '#6b7280', textTransform: 'capitalize' },
    weatherIcon: { width: '60px', height: '60px', marginTop: '-10px', marginRight: '-10px' },
    weatherGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginTop: '1rem' },
    infoCard: { borderRadius: '1rem', padding: '1rem', display: 'flex', alignItems: 'center', gap: '1rem' },
    tempCard: { backgroundColor: '#fff1f2', color: '#be123c' },
    humidityCard: { backgroundColor: '#eff6ff', color: '#2563eb' },
    aiButton: { marginTop: '1.5rem' },
    aiAdvice: { marginTop: '1.5rem', backgroundColor: '#faf5ff', padding: '1.5rem', borderRadius: '1rem', display: 'flex', gap: '1rem', alignItems: 'flex-start', border: '1px solid #e9d5ff' },
    aiAdviceIconContainer: { backgroundColor: '#e9d5ff', borderRadius: '9999px', padding: '0.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
    aiAdviceTitle: { margin: '0 0 0.5rem 0', fontWeight: 600, color: '#5b21b6', },
    aiAdviceText: { margin: 0, color: '#4b5563', lineHeight: '1.6' },
    cardTitle: { marginTop: 0, fontWeight: 600, paddingBottom: '0.5rem' },
    historyCard: { maxHeight: 'calc(100vh - 12rem)', overflowY: 'auto' },
    historyList: {listStyleType: 'none',padding: 0,margin: '0 0.5rem 0 0', maxHeight: '400px',overflowY: 'auto',},
    historyItem: { display: 'flex', alignItems: 'center', gap: '1rem', padding: '1rem', backgroundColor: '#f8fafc', borderRadius: '1rem', marginBottom: '0.75rem' },
    historyTempBubble: { backgroundColor: '#e0e7ff', color: '#4338ca', padding: '0.5rem 0.75rem', borderRadius: '9999px', fontWeight: '600', fontSize: '0.875rem' },
    historyCity: { fontWeight: 600, color: '#1e293b' },
    historyDesc: { margin: 0, color: '#64748b', textTransform: 'capitalize', fontSize: '0.875rem' },
    historyDate: { color: '#64748b', fontSize: '0.875rem', marginLeft: 'auto' },
    authToggle: { background: 'none', border: 'none', color: '#4f46e5', cursor: 'pointer', marginTop: '1rem', padding: 0, fontWeight: 600 },
    planTag: { display: 'inline-block', padding: '0.25rem 0.75rem', borderRadius: '9999px', fontSize: '0.75rem', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'white' },
    freeTag: { color: '#4b5563', backgroundColor: '#e5e7eb' },
    premiumTag: { background: 'linear-gradient(to right, #f97316, #f59e0b)', boxShadow: '0 2px 8px rgba(249, 115, 22, 0.4)' },
    proTag: { background: 'linear-gradient(to right, #1e3a8a, #4f46e5)', boxShadow: '0 2px 8px rgba(79, 70, 229, 0.4)' },
    freemiumMessage: { backgroundColor: '#eef2ff', color: '#4338ca', padding: '1rem', borderRadius: '0.75rem', marginBottom: '1rem', textAlign: 'center', fontSize: '0.875rem' },
    upgradeButton: { display: 'inline-flex', alignItems: 'center', gap: '0.5rem', background: 'linear-gradient(to right, #f59e0b, #ef4444)', color: 'white', border: 'none', borderRadius: '0.75rem', padding: '0.5rem 1rem', fontWeight: '600', cursor: 'pointer', transition: 'transform 0.2s ease-in-out', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)'},
    aiAdviceText: {margin: 0,color: '#4b5563',lineHeight: '1.6',whiteSpace: 'pre-wrap',},
};  